include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FreeFallRootlessPrefs
FreeFallRootlessPrefs_FILES = FFRRootListController.m
FreeFallRootlessPrefs_FRAMEWORKS = UIKit
FreeFallRootlessPrefs_PRIVATE_FRAMEWORKS = Preferences
FreeFallRootlessPrefs_INSTALL_PATH = /Library/PreferenceBundles
FreeFallRootlessPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
